Update cookbook.rst
novuhq/novu-python pull request #101
Opened 2023-10-15 14:34 UTC by HarshMN2345

This pull request introduces improvements to the project's documentation. It refactors the existing content in the Cookbook section to make it more readable and understandable. The information is now presented in a structured format with clear instructions on how to change API request timeouts and take control over the session of requests.

2023-10-27 14:52 UTC, HarshMN2345 commented
@davidsoderberg pls review it

2023-10-27 22:42 UTC, ryshu requested changes
Please read contribution guideline

PR should be directed on alpha branch.

Their is also a commit convention

2023-10-27 22:42 UTC, ryshu commented on docs/guides/cookbook.rst
> +Subscribe to us right away to receive up-to-date information about the Logto Cloud (SaaS) as well as in-time feature updates.
?

2023-10-27 22:42 UTC, ryshu commented on docs/guides/cookbook.rst
> +Here's an example of setting up an automatic retry mechanism for requests with specific HTTP status codes (502, 503, 504)::
If you want to change the RST documentation, you must keep the sphinx syntax.

cf: https://www.sphinx-doc.org/en/master/

For example, the use of example block is done via the code-block: https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-code-block

```suggestion
Here's an example of setting up an automatic retry mechanism for requests with specific HTTP status codes (502, 503, 504):

.. code-block:: python
```

2023-10-27 22:42 UTC, ryshu commented on docs/guides/cookbook.rst
> +Sometimes, you may need to perform advanced operations using a ``requests.Session``.
References to other documentation must be kept. Otherwise the reader must search themselves and may end up in the wrong place.

```suggestion
Sometimes, you may need to perform advanced operations using a :class:`~requests.Session`.
```

2023-10-27 22:42 UTC, ryshu commented on docs/guides/cookbook.rst
> +    EventApi(..., ..., request_timeout=60).trigger_bulk(...)
All exemple in code block

```suggestion
.. code-block::

    EventApi(..., ..., request_timeout=60).trigger_bulk(...)
```

2023-10-27 22:42 UTC, ryshu commented on docs/guides/cookbook.rst
> +Pass `requests_timeout` as a keyword argument during initialization.
Should be written in sphinx

```suggestion
Pass ``requests_timeout`` as a keyword argument during initialization.
```

2023-10-27 22:42 UTC, ryshu commented on docs/guides/cookbook.rst
> +Set the environment variable `NOVU_PYTHON_REQUESTS_TIMEOUT` to define the timeout in seconds. This will override all timeouts in this package.
Should be written in sphinx

```suggestion
Set the environment variable ``NOVU_PYTHON_REQUESTS_TIMEOUT`` to define the timeout in seconds. This will override all timeouts in this package.
```

2023-10-27 22:42 UTC, ryshu commented on docs/guides/cookbook.rst
> +You can adjust the timeout for API requests made with the `requests` module in two ways:
Should be written in sphinx

```suggestion
You can adjust the timeout for API requests made with the :module:`requests` module in two ways:
```

2023-10-29 07:15 UTC, HarshMN2345 commented
@ryshu i am adding a new PR with the changes you asked

2023-10-29 07:15 UTC, closed without merging