Removed pylint directive and added clear configuration method
novuhq/novu-python pull request #126
Opened 2023-10-17 13:53 UTC by Akshat111111

2023-10-22 12:50 UTC, ryshu requested changes
In personal opinion, this MR does not bring much to the bookstore but why not.

However, you must take the time to follow the contribution code. Here it is very easy for me to see that these have not been read:

* commit name is not correct
* code formatting is not applied, implying that pre-commit is not installed
* the branch is directed to main, where they must be directed to alpha
* the code is not tested

The description doesn't explain at all what this change does:

1. Here, we put getters/setters which serve no purpose (apart from adding code to maintain and reading complexity)
2. Add a `clear_configuration` method which sets the fields to "" values

Check with the depot managers but for me these changes are not useful at all and do not address any needs.

@Cliftonz @unicodeveloper WDYT ?

2023-10-22 12:50 UTC, ryshu commented on novu/config.py
> +class NovuConfig(metaclass=Singleton):                                           # pylint: disable=R0903
Does not respect the indentation imposed by black to standardize the code

2023-10-22 12:50 UTC, ryshu commented on novu/config.py
> +    def url(self):
Is not documented, although the field was before

2023-10-22 12:50 UTC, ryshu commented on novu/config.py
> +    def api_key(self):
Is not documented, although the field was before

2023-10-22 12:50 UTC, ryshu commented on novu/config.py
> +            url (str): The URL of the Novu API to reach.
Duplication of typing which is not useful

2023-10-22 12:50 UTC, ryshu commented on novu/config.py
> +            api_key (str): The API Key required to authenticate with the Novu API.
Duplication of typing which is not useful

2023-10-22 12:50 UTC, ryshu commented on novu/config.py
>      def configure(cls, url: str, api_key: str):
The return is not documented

2023-10-25 11:03 UTC, Akshat111111 commented on novu/config.py
>      def configure(cls, url: str, api_key: str):
Sure, I will definately take care of the above points and will change it accordingly

2024-01-19 11:38 UTC, closed without merging