Update make.bat
novuhq/novu-python pull request #152
Opened 2023-11-02 04:10 UTC by Atharva1723

I've updated the URL in the error message to provide a more specific and up-to-date link to the Sphinx documentation related to installation. The new URL points directly to the "Installation" section of the documentation, making it easier for users to find the information they need to resolve the issue.

**Why this change is necessary**:
The current URL points to the root of the Sphinx documentation website, which is less specific and might not provide immediate guidance for users facing an installation issue. The updated URL ensures that users are directed to the correct section, improving their experience and reducing the chances of confusion.

**The new URL uses "https://" for a secure connection.**
This change is a minor improvement that enhances the user experience when encountering installation issues with Sphinx.

2023-11-02 18:36 UTC, Atharva1723 commented
@ryshu Please review this PR! Thank You :)

2023-11-04 13:20 UTC, Atharva1723 commented
@ryshu Can you Please review this PR ? Thank You :)

2023-11-06 19:18 UTC, ryshu requested changes
Hi,

For me there is no need to reinvent the wheel on this file because it is autogenerated.

If you find that the documentation is not adequate, you might as well submit an issue directly to the Sphinx repository so that their codes can be updated: https://github.com/sphinx-doc/sphinx

From my point of view, there is a very good reason for not putting a full URL here: if the documentation link changes, the previous code is still good while the proposed code is no longer good.

The https has since been corrected on their repositories in fact, we can correct it here, but for me the modification must be a copy and paste of this file: https://github.com/sphinx-doc/sphinx/blob/master/doc/make.bat

2023-11-07 02:48 UTC, Atharva1723 commented
> Hi,
> 
> For me there is no need to reinvent the wheel on this file because it is autogenerated.
> 
> If you find that the documentation is not adequate, you might as well submit an issue directly to the Sphinx repository so that their codes can be updated: https://github.com/sphinx-doc/sphinx
> 
> From my point of view, there is a very good reason for not putting a full URL here: if the documentation link changes, the previous code is still good while the proposed code is no longer good.
> 
> The https has since been corrected on their repositories in fact, we can correct it here, but for me the modification must be a copy and paste of this file: https://github.com/sphinx-doc/sphinx/blob/master/doc/make.bat

Yes, it is better to include the relative url  as it ensures that the link will still work within the context of the file, even if the actual documentation location changes.

2023-11-07 05:22 UTC, unicodeveloper commented
So can we close this PR now?

2023-11-07 05:38 UTC, Atharva1723 commented
> So can we close this PR now?

Actually i have made an fresh commit that updates the bat file according to the sphinx original file

2023-11-07 05:40 UTC, unicodeveloper commented
We appreciate your efforts. However, there are other issues that are priority that you can handle. Updating this right now does not provide the users of this SDK any value. So, please can you look into the issues, we have things that can be documented and features that can be added to the SDK. Sorry about this @Atharva1723

2023-11-07 11:07 UTC, ryshu commented on docs/make.bat
> +	set SPHINXBUILD=python ../sphinx/cmd/build.py
I think this line only work on sphinx repositiory

```suggestion
	set SPHINXBUILD=sphinx-build

```

2023-11-07 11:14 UTC, ryshu approved these changes

2023-11-07 11:15 UTC, merged