feat: bulk create subscribers
novuhq/novu-python pull request #63
Opened 2023-09-28 09:45 UTC by devblin

Implements: #59

2023-09-28 09:46 UTC, devblin commented
@unicodeveloper

2023-09-30 17:29 UTC, Cliftonz commented
Hey sorry for the slow responce, feel free to ping me and @unicodeveloper  in the future.

2023-09-30 17:30 UTC, Cliftonz submitted a review, later dismissed

2023-10-04 20:25 UTC, ryshu requested changes
you might rebase your branch on `alpha` to pass test (I fix configuration of codespell which fail on main)

2023-10-04 20:25 UTC, ryshu commented on novu/api/subscriber.py
> +    def bulk_create(self, subscribers: List[SubscriberDto]) -> Dict[str, Iterator[SubscriberDto]]:
Wrongly typed, it's an Generator which is return by the bulk_create (see unit tests).

I think it might be a good idea to make the API return more explicit rather than leaving our clients in the dark here. The list of fields in the dictionary is finite: "created", "updated", "failed"

Either by serializing response in a TypedDict or a Dto

2023-10-04 20:25 UTC, ryshu commented on novu/api/subscriber.py
> +    def bulk_create(self, subscribers: List[SubscriberDto]) -> Dict[str, Iterator[SubscriberDto]]:
Also, subscribers should be typed as an Iterator, which allow your user to provide any object that provide the [__iter__()](https://docs.python.org/3/library/stdtypes.html#iterator.__iter__) and [__next__()](https://docs.python.org/3/library/stdtypes.html#iterator.__next__) methods

See https://docs.python.org/3/library/collections.abc.html?highlight=iterator#collections.abc.Iterator

2023-10-14 14:24 UTC, ryshu commented
@devblin @Cliftonz

I updated the MR to make it work fine after rebasing it to alpha.

I applied the recommendations that I had previously proposed and we now have the result of bulk_create directly in the DTO definition (which therefore allows us to clearly understand what is happening and what is being responded to by the API) .

It's ready to be merge

2023-10-14 14:24 UTC, ryshu approved these changes

2023-10-14 15:07 UTC, unicodeveloper commented
Conflicts need to be resolved here @ryshu

2023-10-14 15:10 UTC, ryshu commented
> Conflicts need to be resolved here @ryshu

Should be ok

2023-10-14 15:12 UTC, unicodeveloper approved these changes

2023-10-14 15:13 UTC, merged