Added the delete_credentials method to the SubscriberApi class to allow deleting user credentials.
novuhq/novu-python pull request #65
Opened 2023-10-01 14:00 UTC by MuhammadNFadhil

2023-10-02 06:19 UTC, MuhammadNFadhil commented
@Cliftonz  @unicodeveloper

2023-10-04 15:20 UTC, Cliftonz commented
@MuhammadNFadhil Looks like the CI is failing I would take a look at the output see what is going on and make a push.

2023-10-04 20:14 UTC, ryshu requested changes
Like @Cliftonz say, missing unit tests

Please take care to rename your commit following the contribution guidelines: https://github.com/novuhq/novu-python/blob/main/CONTRIBUTING.rst

2023-10-04 20:14 UTC, ryshu commented on novu/api/subscriber.py
> +        )
It doesn't match API SPEC, which indicate that this action doesn't return any data

https://api.novu.co/api/#/Subscribers/SubscribersController_deleteSubscriberCredentials

2023-10-04 20:14 UTC, ryshu commented on novu/api/subscriber.py
> +        )
```suggestion
        self.handle_request("DELETE", f"{self._subscriber_url}/{subscriber_id}/credentials/{provider_id}")
```

2023-10-04 20:14 UTC, ryshu commented on novu/api/subscriber.py
> +    ) -> SubscriberDto:
```suggestion
    ) -> None:
```

2023-10-06 22:56 UTC, ryshu commented
Hi @MuhammadNFadhil ,

Ok for the code but tests are still missions. You need to implement them.

2023-10-14 14:05 UTC, ryshu commented
@MuhammadNFadhil @Cliftonz Updated to match all requirements (CI/CD, unit tests)

Ready to be "rebase and merge" in alpha

2023-10-14 14:05 UTC, ryshu approved these changes

2023-10-14 15:11 UTC, merged