feat: add blueprint methods
novuhq/novu-python pull request #90
Opened 2023-10-06 15:22 UTC by Yash-sudo-web

Addresses Issue #79

2023-10-07 03:59 UTC, Yash-sudo-web commented
hey @ryshu, how to proceed with this now, can you brief me a bit?

2023-10-07 14:28 UTC, Yash-sudo-web commented
I updated the code according to the linter, can you re-run the tests and let me know if there are still any issues?

2023-10-07 14:33 UTC, ryshu commented
Hi, you can run all pipelines tests on your own computer if you want.

Still missing all tests, pipelines will fail. 100÷ coverage is required to pass pipelines.

2023-10-07 17:07 UTC, Yash-sudo-web commented
Hello, I have added the unittests for the blueprint methods, test coverage should be 100+ now.

2023-10-08 12:48 UTC, Yash-sudo-web commented
hey @ryshu, can you review the PR? I am facing some issues with implementation of a unit test, one of them works fine but the other one is not passing.

2023-10-09 06:49 UTC, ryshu requested changes
When I look at the history, I see that the commits you make don't follow the naming convention.

I also observe that the merge request is targeted towards the "main" branch while we use the "alpha" branch for current developments.

Since all of these points are covered in the contribution guidelines, I would like you to take a look at them before asking for my help. https://github.com/novuhq/novu-python/blob/main/CONTRIBUTING.rst

For the unit test part, the unit test fails and shows the error you are making. Since it is enough to read the result to understand the error, I don't see where I can be useful.

![image](https://github.com/novuhq/novu-python/assets/22155261/172c7a12-bde8-48ce-a86d-0b78b3f9918a)

Result doesn't match your expectation.

FYI, for debug purpose only (should never be comited), you can use `self.maxDiff = None` before the test to see the untruncated message. https://docs.python.org/3/library/unittest.html#unittest.TestCase.maxDiff

2023-10-09 06:49 UTC, ryshu commented on novu/dto/__init__.py
> +    "BlueprintDto",
They are in alphabetical order here normally

2023-10-09 06:49 UTC, ryshu commented on novu/api/__init__.py
> +    "BlueprintApi",
They are in alphabetical order here normally

2023-10-09 06:49 UTC, ryshu commented on tests/api/test_blueprint.py
> +        general=[{}],
API return and expectation aren't the same here. You expect and empty general when the API return blueprint DTO

2023-10-09 06:49 UTC, ryshu commented on novu/dto/blueprint.py
> +    general: List[BlueprintDto] = dataclasses.field(default_factory=list)
This is not the correct way to code a list field containing a DataClass. You have to look at the other DTOs to understand how it is used (in the code, look at `DtoIterableDescriptor`)

2023-10-09 06:49 UTC, ryshu commented on novu/dto/blueprint.py
> +    popular: List[BlueprintDto] = dataclasses.field(default_factory=list)
Same here

2023-10-09 12:07 UTC, Yash-sudo-web commented on novu/dto/__init__.py
> +    "BlueprintDto",
Done

2023-10-09 12:07 UTC, Yash-sudo-web commented on novu/api/__init__.py
> +    "BlueprintApi",
Done

2023-10-09 12:17 UTC, Yash-sudo-web commented on novu/dto/blueprint.py
> +    general: List[BlueprintDto] = dataclasses.field(default_factory=list)
Done

2023-10-09 12:17 UTC, Yash-sudo-web commented on novu/dto/blueprint.py
> +    popular: List[BlueprintDto] = dataclasses.field(default_factory=list)
Done

2023-10-14 14:26 UTC, ryshu commented
@Yash-sudo-web Do you want me to finish your MR? The unit tests don't seem to be too complex for me to solve and we can plan a new alpha quickly.

2023-10-14 14:45 UTC, Yash-sudo-web commented
hey, @ryshu yes you can finish the MR, thanks.

2023-10-14 15:05 UTC, ryshu approved these changes

2023-10-14 15:05 UTC, ryshu commented
@Cliftonz Hi, also ready for rebase and merge

2023-10-14 15:06 UTC, merged